# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"md5_update_from_file": "00_core.ipynb",
         "md5_file": "00_core.ipynb",
         "md5_update_from_dir": "00_core.ipynb",
         "md5_dir": "00_core.ipynb",
         "hashes": "00_core.ipynb",
         "ProgressParallel": "00_core.ipynb",
         "lazy_unpack": "00_core.ipynb",
         "unpack_body_models": "00_core.ipynb",
         "fast_amass_unpack": "00_core.ipynb",
         "npz_paths": "00_core.ipynb",
         "viable_slice": "00_core.ipynb",
         "npz_contents": "00_core.ipynb",
         "AMASS": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gra.ygav.in/llamass/"

git_url = "https://github.com/gngdb/llamass/tree/master/"

def custom_doc_links(name): return None
