# AUTOGENERATED! DO NOT EDIT! File to edit: 06_dip.ipynb (unless otherwise specified).

__all__ = ['SMPL_ForwardKinematics_Sparse', 'iter_pkl_in']

# Cell
import os
import pickle
from pathlib import Path
import numpy as np
import torch
import llamass.core
import llamass.transforms
from einops import repeat, rearrange
from scipy.spatial.transform import Rotation as R

# Cell
class SMPL_ForwardKinematics_Sparse(llamass.transforms.SMPL_ForwardKinematics):
    def from_sparse_rotmat(self, joint_angles):
        mj, nj = self.major_joints, self.n_joints
        return self.from_rotmat(sparse_to_full(joint_angles, mj, nj, rep="rotmat"))

    def from_sparse_aa(self, joint_angles):
        mj, nj = self.major_joints, self.n_joints
        return self.from_aa(sparse_to_full(joint_angles, mj, nj, rep="aa"))

# Cell
def iter_pkl_in(dip_dir):
    # open a random pickle file in the DIPS dataset
    example_file = None
    for dirpath, dirnames, filenames in os.walk(dips_path):
        dirpath = Path(dirpath)
        for filename in filenames:
            filename = Path(filename)
            if not filename.is_dir() and filename.suffix == ".pkl":
                yield dirpath/filename